arcana-network/developer-dashboard

src/App.vue
src/assets/iconography/close.svg
src/components/AppHeader.vue
src/components/LandingDescriptor.vue
src/components/app-configure/AppAuth.vue
src/components/app-configure/AppName.vue
src/components/lib/VCardButton/VCardButton.vue
src/components/lib/VChip/VChip.vue
src/components/lib/VDropdown/VDropdown.vue
src/components/lib/VSwitch/VSwitch.vue
src/components/lib/styles/__style-guide.css
src/pages/AppConfigure.vue

1. Added new close icon
2. Removed description from login page sidebar
3. Updated login type input fields to closely match the updated design. Currently not matching exactly
4. Updated buttons in login Type. Added clear button to clear input fields
5. Added keyup.enter event for app name
6. Removed background and box shadow styling on hover of card button
7. Made scrollbar track transparent
8. Adjusted styling for v-switch

Ar 610 new layout for login type

---

src/pages/AppConfigure.vue
src/pages/AppLoginV2.vue
src/router/index.js

Replaced router.replace by router.push at appropriate places to maintain history stack instead of replacing it.
Need router.replace in router/index.js when routing from any page to /login page
Also removed twitter and reddit logins from login page

Replaced router.replace by router.push

---

public/tx-sign.js
vite.config.js

1. Updated Dashboard Signer
2. Added config for building sourcemaps

Sourcemaps and updated signer

---

package-lock.json

**Changes**
- Replace the old package-lock.json with a one generated with Node 16
Resolves AR-812.

Regenerate package-lock.json with Node 16

---

src/App.vue
src/pages/AppConfigure.vue
src/pages/AppLoginV2.vue
src/pages/AppNewPassword.vue
src/pages/AppProfile.vue
src/router/index.js
src/store/auth.store.js
src/utils/cryptoUtils.js

PR is quite big.
1. Added password page after login so that we can encrypt the user's private key with that password and store it in local storage
2. Login sessions are maintained if accessToken is present in local storage, else user needs to go through login flow
3. Whenever user enters the configure page after session ends, he'll be asked to enter the password to decrypt the private key in his localstorage. If he enters wrong password, he won't be allowed to proceed. Moreover there is forget password button which will clear storage and take user again to login flow
4. If access token is present, app details are fetched in App.vue and pushed to store from there itself instead of fetching it in AppConfigure
5. Access Tokens are encoded and stored in localstorage and decoded when required. …

Ar 760 login session

---

src/pages/AppDashboard.vue

Changed 'Weekly' to 'Daily' in dashboard graph as it was confusing for users to get daily data in Weekly graph
ref: https://team-1624093970686.atlassian.net/browse/AR-854?atlOrigin=eyJpIjoiNGM2Yjc4M2MyNjU1NGQ0ZWI5NzllZTE5NTVhYWI5Y2UiLCJwIjoiaiJ9

Changed weekly to daily in dashboard graph

---

src/components/AppHeader.vue
src/pages/AppDashboard.vue

Needed to change back ups to backups, since both can have seperate meaning
ref: https://team-1624093970686.atlassian.net/browse/AR-872?atlOrigin=eyJpIjoiYTVjZjdmYWQxMjNiNGJhYWIzN2ZlYzhjZDI2ZWJmYTkiLCJwIjoiaiJ9

Renamed back ups to backups as it is a single word

---

src/pages/AppProfile.vue

JIRA Ticket: https://team-1624093970686.atlassian.net/browse/AR-804?atlOrigin=eyJpIjoiYTljOTY5YTIxZTU5NDc2ZGJjZDgyZTNjZGNkMTY3NTAiLCJwIjoiaiJ9
1. Added new property `sizeErr` to `organisationDetails`,
1. Check if the inputted size is a. safe integer, b. finite (i.e. no NaN or Infinity), c. positive
1. If not, then show error to user via `sizeErr`

Validate organization sizes

---

src/App.vue
src/pages/AppDashboard.vue
src/services/app-config.service.js

1. Refactored the code a bit, there was repetition, so moved it to a single place and called the function in App.vue and AppDashboard.vue
2. Added logic for converting value to MB if it is less than 1023 MB else it'll be converted to GB
ref: https://team-1624093970686.atlassian.net/browse/AR-907

Display storage and bandwidth in MB and GB

---

src/pages/AppProfile.vue

1. Added Ellipsis to overflowing text elements
2. Added title to show entire text on hover
ref: https://team-1624093970686.atlassian.net/browse/AR-855

Added text overflow ellipsis

---

src/pages/AppDashboard.vue

Ticket: https://team-1624093970686.atlassian.net/browse/AR-738?atlOrigin=eyJpIjoiOTI1Y2YxMWJkYzhmNDM0ZGIxYjc0ZjgwODFlZTM5OTMiLCJwIjoiaiJ9

Update typography and styling for the Getting Started message

---

src/components/AppHeader.vue
src/components/icons/CloseIcon.vue

Ticket: https://team-1624093970686.atlassian.net/browse/AR-736?atlOrigin=eyJpIjoiMjMxNmZjNTYwNWJhNDU2YTkzODU0YjNiMjlhMDAyNWIiLCJwIjoiaiJ9

Use actual close icon at the top header disclaimer

---

src/pages/AppConfigure.vue

JIRA Ticket: https://team-1624093970686.atlassian.net/browse/AR-733?atlOrigin=eyJpIjoiNThiODY4MDQxZDFhNDdlZmI3ZTIyMGNlNTJhOWRkOTUiLCJwIjoiaiJ9
1. Updated inline styles according to Figma.

Update Learn More Styling

---

src/pages/AppProfile.vue

JIRA Ticket: https://team-1624093970686.atlassian.net/browse/AR-737?atlOrigin=eyJpIjoiYjE2ZGViMGJjNDI2NGY1OWJhYjE2ZTY5YTAxNzljOGYiLCJwIjoiaiJ9

Update Organization UI

---

src/pages/AppDashboard.vue

This one fell through the cracks as I reverted this change during development.
Ticket: https://team-1624093970686.atlassian.net/browse/AR-738?atlOrigin=eyJpIjoiNjdmNDliZWEyYjM0NDE3ZmI0YTBkNjY2MThiM2QyMTIiLCJwIjoiaiJ9 (See https://team-1624093970686.atlassian.net/browse/AR-738?focusedCommentId=10263)

Fix isConfigured

---

src/components/lib/VDropdown/VDropdown.vue

Ref: https://team-1624093970686.atlassian.net/browse/AR-871

Replaced cursor grab with cursor default

---

src/components/app-configure/AppName.vue

Ticket [AR-869](https://team-1624093970686.atlassian.net/browse/AR-869?atlOrigin=eyJpIjoiMzg5NDBiYTQ2MjllNDIwM2FlMDE2NmRmZDM2ZWYxNDgiLCJwIjoiaiJ9)
Adjusted spacing between app name and its input field to make it more visible

AR-869 App Name design fix while creating the app

---

src/components/lib/VDropdown/VDropdown.vue

Resolves [AR-870](https://team-1624093970686.atlassian.net/browse/AR-870).
Added an event listener on document body, close dropdown on click

Added listener to close dropdown on document click

---

src/pages/AppUsers.vue

Resolves [AR-1004](https://team-1624093970686.atlassian.net/browse/AR-1004).
- [AR-778](https://team-1624093970686.atlassian.net/browse/AR-778)
1. Renamed the function to searchUsersByWalletAddress
2. Added event listener for enter key press
3. In case of null return blank array instead of doing nothing. The null check was already added using optional chaining operator

Handled null responses from search api

---

package.json
src/components/app-configure/AppChain.vue
src/components/app-configure/AppUserLimits.vue
src/components/lib/VDropdown/VDropdown.vue
src/pages/AppConfigure.vue
src/pages/AppUsers.vue

**Changes**
- [AR-870](https://team-1624093970686.atlassian.net/browse/AR-870) resolved by #38 
- [AR-1019](https://team-1624093970686.atlassian.net/browse/AR-1019) resolved by #39 
- [AR-1004](https://team-1624093970686.atlassian.net/browse/AR-1004) resolved by #40  
- [AR-868](https://team-1624093970686.atlassian.net/browse/AR-868) resolved by #41 
- [AR-859](https://team-1624093970686.atlassian.net/browse/AR-859) resolved by #43 
Bumped the version number in `package.json` to match.

Production release v0.1.0

---

public/tx-sign.js

Resolves [AR-1494](https://team-1624093970686.atlassian.net/browse/AR-1494).
Replaced Signer function

Updated signer function for making smart contract call

---

src/pages/AppConfigure.vue

Resolves or continues [AR-1444](...).
Removed smart contract call on create app

Removed smart contract call on create app

---

public/tx-sign.js
src/services/app-config.service.js
src/services/auth.service.js
src/services/dashboard.service.js
src/services/get-env-api.js
src/services/profile.service.js
src/services/user.service.js

Resolves [AR-999](https://team-1624093970686.atlassian.net/browse/AR-999).
1. Replaced the unversioned apis with API version 1 (v1)
2. Removed /api prefix from api endpoints wherever applicable
3. Modified getEnvApi method
a. Added version parameter that accepts string or false
b. If version is not supplied, it fallbacks to current version
c. If version is false, then it skips api versioning and returns unversioned raw api
4. Added false to apis that don't need versioning for now
5. Merged [PR#47](https://github.com/arcana-network/developer-dashboard/pull/47) that resolves [AR-1494](https://team-1624093970686.atlassian.net/browse/AR-1494) (public/tx-sign.js)

Replace unversioned apis with versioned apis

---

package.json
public/tx-sign.js
src/components/app-configure/AppChain.vue
src/components/lib/VRadio/VRadio.vue
src/components/lib/VRadioGroup/VRadioGroup.vue
src/pages/AppConfigure.vue
src/services/app-config.service.js
src/services/auth.service.js
src/services/dashboard.service.js
src/services/get-env-api.js
src/services/profile.service.js
src/services/user.service.js
src/utils/constants.js

Resolves  [AR-1559](https://team-1624093970686.atlassian.net/browse/AR-1559).
- [AR-1444](https://team-1624093970686.atlassian.net/browse/AR-1444) resolved by [#44](https://github.com/arcana-network/developer-dashboard/pull/44)
- [AR-1023](https://team-1624093970686.atlassian.net/browse/AR-1023) resolved by [#50](https://github.com/arcana-network/developer-dashboard/pull/50)
- [AR-1024](https://team-1624093970686.atlassian.net/browse/AR-1024) resolved by [#51](https://github.com/arcana-network/developer-dashboard/pull/51)
- [AR-999](https://team-1624093970686.atlassian.net/browse/AR-999) resolved by [#42](https://github.com/arcana-network/developer-dashboard/pull/42)
- [AR-1494](https://team-1624093970686.atlassian.net/browse/AR-1494) resolved by …

Production release v0.1.1

---

src/services/get-env-api.js

Hotfix that resolves issues from [AR-999](https://team-1624093970686.atlassian.net/browse/AR-999)

Hotfix for AR-999

---

public/tx-sign.js
src/pages/AppConfigure.vue

Resolves [AR-1590](https://team-1624093970686.atlassian.net/browse/AR-1590)

Replaced dashboard signer

---

src/components/app-configure/AppAuth.vue
src/pages/AppConfigure.vue
src/pages/AppDashboard.vue
src/services/app-config.service.js
src/store/configure.store.js

Resolve [AR-2031](https://team-1624093970686.atlassian.net/browse/AR-2031).
**Changes**
- Refactors the the AppAuth component a bit for clarity.
- Adds a config for passwordless auth and an origin field.

Add passwordless auth config

---

src/components/app-configure/AppAuth.vue
src/services/app-config.service.js
src/store/configure.store.js

Resolves [AR-1605](https://team-1624093970686.atlassian.net/browse/AR-1605).
[AR-1895](https://team-1624093970686.atlassian.net/browse/AR-1895)
1.  Added a switch that allows developers to choose aggregate login in auth type
2. Switch is active when creating the app and disabled after creation of app (Developers can't change this setting after the app is created)
3. Added sample text in tooltip untils AR-1895 is resolved

Added aggregate login switch

---

src/use/arcanaAuth.ts

Resolves [AR-2379](https://team-1624093970686.atlassian.net/browse/AR-2379).
- Added `redirectUri` option in `AuthProvider.init`. Set `redirectUri` to `window.location.origin/login`

Added redirectUri in options of auth sdk init

---

src/components/app-configure/ConfigureSidebar.vue
src/pages/AppConfigure.vue
src/utils/constants.ts

Resolves [AR-2328](https://team-1624093970686.atlassian.net/browse/AR-2383)
- Added Sidebar component
- Added constants for sidebar tab values

Configure Sidebar

---

src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/SettingCard.vue
src/components/app-configure/general/AppName.vue
src/components/app-configure/general/GeneralSettings.vue
src/components/lib/VCard/VCard.vue
src/components/lib/VSeperator/VSeperator.vue
src/components/lib/VTextField/VTextField.vue
src/components/lib/styles/__style-guide.css
src/pages/AppConfigure.vue
src/router/index.ts
src/store/configure.store.ts
src/store/index.ts
src/store/old-configure.store.ts
src/utils/constants.ts

Resolves [AR-2380](https://team-1624093970686.atlassian.net/browse/AR-2380).
- Renamed existing `configure.store` to `old-configure.store`. This store is not needed anymore, but kept it just to avoid unusual errors while development. Will remove it once redesign is complete
- Created a new `configure.store` that will hold state of the configuration sections
- Moved some state like `appName`, `appId`, `isAppConfigured`, `onConfigChange` and `appNameError` from `store/index.ts` to `configure.store`
- Added `text-uppercase` in style-guide.css
- Modified some props and stylings in `VTextField`, `VCard` and `VSeperator`
- Created a reusable `SettingCard.vue` that can be used for individual setting section
- Created `AppName` section
- Created `GeneralSettings` component that'll render contents …

General > App Name

---

src/App.vue
src/components/app-configure/SettingCard.vue
src/components/app-configure/general/AppControls.vue
src/components/app-configure/general/ConfirmDeletePopup.vue
src/components/app-configure/general/DeleteTimerPopup.vue
src/components/app-configure/general/GeneralSettings.vue
src/store/index.ts

Resolves [AR-2397](https://team-1624093970686.atlassian.net/browse/AR-2397).
- Added Delete button
- Added Confirm delete and progress timer for delete popups
- Added logic for timer. Circular Progress timer triggers every 10ms and actual display timer triggers every 1000ms
- Added Deletion logic
- Added Full screen loader while consuming delete API

Added app controls section

---

src/components/app-configure/auth/AuthSettings.vue
src/components/app-configure/auth/WalletAuth.vue
src/components/lib/styles/__style-guide.css
src/router/index.ts

Resolves [AR-2252](https://team-1624093970686.atlassian.net/browse/AR-2252).
- Added static wallet auth section

Added wallet auth settings

---

src/components/app-configure/auth/AuthSettings.vue
src/components/app-configure/auth/PasswordlessAuth.vue
src/components/lib/styles/__style-guide.css
src/store/configure.store.ts

Resolves [AR-2111](https://team-1624093970686.atlassian.net/browse/AR-2111).
- Added Passwordless auth card
- Added Javascript Origin field with store variable
- Added Redirect URI field with store variable

Passwordless Auth

---

src/components/app-configure/store/AssetEncryption.vue
src/components/app-configure/store/StoreSettings.vue
src/router/index.ts

Resolves [AR-2253](https://team-1624093970686.atlassian.net/browse/AR-2253).
- Added asset encryption section

Added asset encryption section

---

src/components/app-configure/access/AccessSettings.vue
src/components/app-configure/access/ChainType.vue
src/components/app-configure/access/UserAccess.vue
src/components/lib/VCard/VCard.vue
src/router/index.ts
src/store/configure.store.ts
src/utils/constants.ts

Resolves [AR-2255](https://team-1624093970686.atlassian.net/browse/AR-2255) and [AR-2256](https://team-1624093970686.atlassian.net/browse/AR-2256).
- Added static UserAccess section
- Added ChainType Selection section with radio button group and appropriate store operations

Added user access section

---

src/components/app-configure/store/StorageRegion.vue
src/components/app-configure/store/StoreSettings.vue
src/components/lib/VDropdown/VDropdown.vue
src/store/configure.store.ts
src/utils/constants.ts

Resolves [AR-2112](https://team-1624093970686.atlassian.net/browse/AR-2112).
- Added storage region
- Updated styling of VDropdown

Added Storage region

---

src/assets/iconography/link.svg
src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/SettingCard.vue
src/components/app-configure/auth/AggregateLogin.vue
src/components/app-configure/auth/AuthSettings.vue
src/components/app-configure/auth/SocialAuth.vue
src/components/lib/VTextField/VTextField.vue
src/components/lib/styles/__style-guide.css
src/store/configure.store.ts
src/utils/constants.ts

Resolves [AR-2110](https://team-1624093970686.atlassian.net/browse/AR-2110) and [AR-2439](https://team-1624093970686.atlassian.net/browse/AR-2439)
- Added social auth section
- Added aggregate login section

Social Auth and Aggregate Login

---

src/components/app-configure/store/StoreSettings.vue
src/components/app-configure/store/UserLimits.vue
src/components/lib/VDropdown/VDropdown.vue
src/components/lib/VTextField/VTextField.vue
src/store/configure.store.ts
src/utils/constants.ts

Resolves [AR-2249](https://team-1624093970686.atlassian.net/browse/AR-2249).
- Added userlimits section
- Added default limits
- Added logic for limited and unlimited user limit
- Added all the store related changes

User Limits

---

src/components/app-configure/AppAuth.vue

Added a hotfix to make the aggregate login switch work
- Fixed the incorrect props passed to login switch

updated props for aggregate login switch

---

src/utils/signerMakeTx.ts

Resolves [AR-2944](https://team-1624093970686.atlassian.net/browse/AR-2944).
- Append 0x to start of `appAddress` if it doesn't start with 0x

Append 0x to start of app address

---

package-lock.json
package.json
src/pages/AppLogin.vue
src/use/arcanaAuth.ts

Resolves [AR-3016](https://team-1624093970686.atlassian.net/browse/AR-3016).
- Replace auth sdk with auth-core@beta sdk
- Replace auth sdk imports with auth-core sdk imports

Update auth sdk to auth-core sdk

---

package-lock.json
package.json

Updates `@arcana/auth-core` to `0.0.3-beta1`.

Update @arcana/auth-core package

---

src/components/app-configure/CreateApp.vue
src/components/app-configure/store/StorageRegion.vue
src/services/gateway.service.ts

Resolves or continues [AR-3051](https://team-1624093970686.atlassian.net/browse/AR-3051).
- move storage region to create app
- disable storage region on configure page

Move region selection to create app

---

src/components/app-configure/auth/RedirectURI.vue
src/components/app-configure/general/AppBranding.vue
src/components/app-configure/general/AppControls.vue
src/components/lib/VToast/VToast.vue
src/pages/AppDashboard.vue
src/services/gateway.service.ts

Resolves [AR-3049](https://team-1624093970686.atlassian.net/browse/AR-3049).
- Add padding (2rem) to tooltip-container only if messages are present in the stack, else keep padding to 0. This helps tooltip container from staying on top of menu item and making it non clickable. 
(Resolves: https://newfang.slack.com/archives/C03JP0VPGBA/p1655377670560559) https://github.com/arcana-network/developer-dashboard/commit/9a36fe1ade8344a5b032eebf6a0deda70e8f8263
- Add toast message on app deletion https://github.com/arcana-network/developer-dashboard/commit/ea264cefa04321796f572fd5208ed3d409f4203a
- Add toast message on copy https://github.com/arcana-network/developer-dashboard/commit/285cbbd878066e46dd6b624b7eab974960404bba and https://github.com/arcana-network/developer-dashboard/pull/103/commits/ …

Integrate api to remove logo

---

src/components/lib/VDropdown/VDropdown.vue

Resolves [AR-3169](https://team-1624093970686.atlassian.net/browse/AR-3196).
- Add opacity to text and arrow in dropdown when disabled 
Before
After

Added opacity to text and arrow while disabled

---

src/components/AppHeader.vue

Resolves [AR-3395](https://team-1624093970686.atlassian.net/browse/AR-3395).
- Update the disclaimer banner

Update the disclaimer text

---

readme.md

Resolves [AR-3462]
NA
Banner update
- [✅  ] The branch name follows the format: `developer/AR-XXX-issue-name`.
- [ ✅] The changes have been tested locally.

Fix #AR-3462 Banner update in readme

---

package-lock.json
package.json
src/utils/constants.ts

Resolves [AR-3599](https://team-1624093970686.atlassian.net/browse/AR-3599).
- Updated the config for discord to accept client secret
Before
After

Updated the config for discord to accept client secret

---

src/components/app-configure/auth/WebWallet.vue
src/components/lib/VToast/VToast.vue

Revert back to using computed for objects and arrays

Revert back to using computed for objects and arrays

---

src/pages/AppLogin.vue

Fetch app details before creating transaction signer

Fetch app config before creating transaction signer to set app address

---

.vscode/extensions.json
src/components/LandingDescriptor.vue
src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/store/UserLimits.vue
src/components/lib/VButton/VButton.vue
src/components/lib/VDropdown/VDropdown.vue
src/components/lib/VFileUpload/VFileUpload.vue
src/components/lib/VTextField/VTextField.vue
src/pages/AppLogin.vue
src/use/arcanaAuth.ts
src/utils/validation.ts

Resolves [AR-3989](https://team-1624093970686.atlassian.net/browse/AR-3989).
- Moved some inline style to `<style>`
- Changed some props interfaces to types (this gets rid of type error, `Default export of the module has or is using private name 'ConfigureProps'.`)
- Updated font size of text-field, button and dropdown
- Added passwordless login section in AppLogin with validation
- Created validation util where we can put all the validations 
Before
After

Passwordless implementation

---

src/components/AppHeader.vue
src/components/app-configure/CreateApp.vue
src/components/app-configure/general/AppControls.vue
src/pages/AppConfigure.vue
src/pages/AppDashboard.vue
src/pages/AppLogin.vue
src/router/index.ts

Resolves [AR-4007](https://team-1624093970686.atlassian.net/browse/AR-4007).
- Add `:appId` params to the routes for dashboard, configure and users
- Rename /app to /apps
- Pass params while doing router.push

Routing changes

---

src/stores/apps.store.ts

Resolves [AR-4174](https://team-1624093970686.atlassian.net/browse/AR-4174).
Fixes app id not getting set correctly in the redirect url.

Bug: Fix redirect url in auth config page

---

src/pages/ManageApps.vue

Resolves [AR-4296](https://team-1624093970686.atlassian.net/browse/AR-4296).
- Removed lorem ipsum from ManageApps screen

AR-4296 Remove lorem ipsum

---

src/components/app-configure/CreateApp.vue
src/components/app-configure/auth/WebWallet.vue
src/pages/AppDashboard.vue
src/pages/ManageApps.vue
src/services/gateway.service.ts
src/stores/apps.store.ts
src/utils/constants.ts

Resolves [AR-4337](https://team-1624093970686.atlassian.net/browse/AR-4337).
- Update the response of app list (/user-app api)
- Maintain stats/overview in store
- Update dashboard page to show dynamic storage and bandwidth values
- (Addon) Wrap Create app inputs in a flex container

AR-4337 Update app list response

---

package-lock.json
package.json
src/pages/AppLogin.vue
src/pages/AppProfile.vue

- Updated to latest auth sdk
- Added reload after logout so destroyed connection can be restored
- Added 1 second timeout before fetching details from wallet

hotfix login issue

---

env.d.ts
src/App.vue
src/components/AppFooter.vue
src/components/LandingDescriptor.vue
src/components/SocialLinks.vue
src/components/lib/styles/__style-guide.css
src/pages/AppLogin.vue
src/router/index.ts

Resolves [AR-4540](https://team-1624093970686.atlassian.net/browse/AR-4540).
- Added meta in routes to toggle footer elements (Remove social icons if there is a sidebar or landing descriptor)
- Update root App's layout to flex so we can arrange sidebar, main and footer in the app
- Removed social icons from footer and created individual component for reuse in sidebar and landing descriptor
- Updated CSS to match the latest design

AR-4540 update footer

---

src/components/app-configure/access/ChainType.vue
src/components/app-configure/auth/SocialAuth.vue
src/components/app-configure/auth/WebWallet.vue
src/components/app-configure/general/AppName.vue
src/components/app-configure/store/UserLimits.vue
src/services/gateway.service.ts

Resolves [AR-4435](https://team-1624093970686.atlassian.net/browse/AR-4435).
Removed the spread operator for secondary object that updates the main object

AR-4435 Storage Limit bug

---

package-lock.json
package.json

Resolves [AR-4910](https://team-1624093970686.atlassian.net/browse/AR-4910).
Update auth sdk to version **0.1.2**, [ref](https://team-1624093970686.atlassian.net/browse/AR-4883?focusedCommentId=17608)

Update auth sdk to latest

---

package-lock.json
package.json

- Downgrade auth sdk to `0.1.3`

Downgrade auth sdk

---

src/components/lib/VDropdown/VDropdown.vue

- Simplify logic for showing dropdown placeholder by using `v-else`

Update logic for showing dropdown placeholder

---

src/stores/apps.store.ts

Add null check for apps

---

public/signer.js
src/components/app-configure/access/CreateOrEditDelegate.vue
src/components/app-configure/access/DidDelegate.vue
src/components/lib/VDropdown/VDropdown.vue

- Update signer and Add null check to keys

Update signer and Add null check to keys

---

src/pages/AppUsers.vue
src/services/gateway.service.ts

- Add offset and count in user list to solve the errors thrown by gateway

Add offset and count to users list

---

src/components/AppHeader.vue
src/components/app-configure/auth/SocialAuth.vue
src/pages/AppDashboard.vue
src/services/gateway.service.ts
src/stores/apps.store.ts
src/use/arcanaAuth.ts
src/utils/chart.ts

Resolves [AR-5450](https://team-1624093970686.atlassian.net/browse/AR-5450).
- Watch route changes and update the Dashboard if app id is updated
- Update chart view to show chart if it exist
[AR-5450]: https://team-1624093970686.atlassian.net/browse/AR-5450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bug fix AR-5450 - Watch route change and update the dashboard

---

src/components/app-configure/auth/SocialAuth.vue
src/components/app-configure/general/AppName.vue

- Remove smart contract calls when saving config

Remove smartcontract calls for app name and social auth

---

env.d.ts
src/use/arcanaAuth.ts

- Added temporary config for mainnet because we can't update auth sdk in dashboard till NoUI sdk is built

Add temporary config for mainnet

---

src/components/SwitchToMainnetConfirmation.vue
src/components/app-configure/general/AppDelete.vue
src/components/lib/VRadio/VRadio.vue
src/pages/AppDashboard.vue
src/pages/AppDetails.vue
src/pages/ManageApps.vue
src/services/gateway.service.ts
src/stores/apps.store.ts
src/utils/createAppConfig.ts

- Use VRadio instead of html radio as it is already styled to theme
- When renaming app name rename it on both networks
- When deleting app delete it on both networks
- Add Legend for MAU progressbar in Manage Apps
- Copy logos from testnet and update it to mainnet on mainnet app creation

Fix UI and functional issues on switch network

---

src/App.vue
src/pages/AppDownNotification.vue
src/router/index.ts

-  Created a route for maintenance and show it before auth is initialised

Toggle maintenance is app down

---

src/pages/AppDashboard.vue

Resolves or continues [AR-5423](https://team-1624093970686.atlassian.net/browse/AR-5423).
1. Changed description.
2. Replaced links
3. Added two more items but commented out as there is no thumbnail images
[AR-5423]: https://team-1624093970686.atlassian.net/browse/AR-5423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-5423] Add correct doc links in the dashboard

---

src/App.vue
src/pages/AppDownNotification.vue
src/router/index.ts

Dev main merge conflicts fix

---

src/components/AppFooter.vue

Fix footer issues

---

src/components/app-configure/ConfigureSidebar.vue

Update footer links

---

src/use/arcanaAuth.ts

Add mainnet network config

---

src/components/app-configure/AppKeyspace.vue

- Set unpartition global to true

Global keyspace value to true

---

index.html
netlify.toml
src/stores/apps.store.ts

Resolves  [AR-5552](https://team-1624093970686.atlassian.net/browse/AR-5552).
1. Added CSP through meta tag.
2. Added Content type and Frame options through `netlify.toml` file
[AR-5552]: https://team-1624093970686.atlassian.net/browse/AR-5552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-5552] add custom headers

---

netlify.toml

1. Add googletagmaner.com to CSP

add gtag-manager domain

---

netlify.toml

Added arcana.network to img-src csp

add arcana.network to img-src csp

---

netlify.toml

- Allow mailchimp csp to execute

Allow mailchimp csp to execute

---

src/pages/AppDashboard.vue

- Update app address to client id (eg: xar_dev_xxxxxxxxxxxxxxx)

Update app address to client id

---

src/components/app-configure/auth/SocialAuth.vue
src/services/gateway.service.ts
src/utils/constants.ts
src/utils/createAppConfig.ts

Resolves [AR-5645(https://team-1624093970686.atlassian.net/browse/AR-5645).
1. Implemented UI and logic to enable input for AWS Cognito credentials.

[AR-5645] Implement logic get AWS Cognito credentials

---

src/components/app-configure/auth/SocialAuth.vue
src/services/gateway.service.ts
src/utils/constants.ts
src/utils/createAppConfig.ts

Reverts arcana-network/developer-dashboard#202

Revert "[AR-5645] Implement logic get AWS Cognito credentials"

---

src/components/app-configure/auth/SocialAuth.vue
src/services/gateway.service.ts
src/utils/constants.ts
src/utils/createAppConfig.ts

Reverts arcana-network/developer-dashboard#204

Revert "Revert "[AR-5645] Implement logic get AWS Cognito credentials""

---

env.d.ts
index.html
netlify.toml
src/components/DeleteCardConfirmPopup.vue
src/components/app-configure/ConfigureActionButtons.vue
src/components/lib/styles/__style-guide.css
src/pages/AppInvoices.vue
src/pages/AppProfile.vue
src/router/index.ts
src/services/gateway.service.ts
src/utils/constants.ts

Resolves [AR-5421](https://team-1624093970686.atlassian.net/browse/AR-5421).
- Integrated stripe to save card
- Added list cards and delete card apis and views
- Added Invoices view where user can list previous invoices, download it and view upcoming bill (Currently upcoming bill is static)
**Add Card**
**View Card Details**
**List Invoices**
**See Invoice details**
[AR-5421]: https://team-1624093970686.atlassian.net/browse/AR-5421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AR-5421 - Billing (Cards and Invoices)

---

src/pages/AppProfile.vue
src/utils/constants.ts

- Hide Adding cards and Invoices temporarily

Remove billing and invoices

---

src/components/app-configure/general/AppDelete.vue

Resolves or continues [AR-5587](https://team-1624093970686.atlassian.net/browse/AR-5587).
1. Remove the app from local store after successfully deleting in backend.
[AR-5587]: https://team-1624093970686.atlassian.net/browse/AR-5587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-5587] Delete app issue reported by QA

---

src/components/app-configure/general/AppDelete.vue
src/pages/AppProfile.vue

- Delete appropriate app from appropriate network instead of specifying static values
- Update logic for checking if billing address is present in server

[HOTFIX] Fix delete app issue

---

src/App.vue
src/components/AppNotifications.vue
src/components/app-configure/auth/SocialAuth.vue
src/pages/AppDashboard.vue
src/pages/AppInvoices.vue
src/pages/AppLogin.vue
src/router/index.ts
src/services/gateway.service.ts
src/stores/apps.store.ts

1. Implemented code to stop event bubbling on clicking download button

[HotFix] Download button expand

---

src/services/gateway.service.ts

1. Update notification read api endpoint.
- [] The branch name follows the format: `developer/AR-XXX-issue-name`.

[Hotfix] update api endpoint

---

src/components/AppHeader.vue
src/components/AppNotifications.vue
src/components/AppNotificationsItem.vue
src/components/icons/NotificationIcon.vue
src/pages/AppDetails.vue
src/pages/AppProfile.vue
src/pages/ManageApps.vue
src/stores/apps.store.ts

Resolves or continues [AR-5948](https://team-1624093970686.atlassian.net/browse/AR-5948).
Implemented fixes and changes for the things mentioned in the ticket. 
[AR-5948]: https://team-1624093970686.atlassian.net/browse/AR-5948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-5948] dashboard notifications feedback fixes

---

src/components/app-configure/AppKeyspace.vue

Resolves [AR-5993](https://team-1624093970686.atlassian.net/browse/AR-5993).
- Updated description of global keys
[AR-5993]: https://team-1624093970686.atlassian.net/browse/AR-5993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[hotfix] AR-5993 update global keys desc

---

src/App.vue
src/use/arcanaAuth.ts

- Use appropriate rpc and chain in auth provider (Polygon Mumbai for testnet and dev and Polygon Mainnet for mainnet)

Use appropriate rpc and chain in auth provider

---

src/components/AppNotifications.vue
src/components/AppNotificationsItem.vue
src/components/lib/styles.css
src/pages/AppDetails.vue
src/pages/AppInvoices.vue
src/pages/AppLogin.vue

1. Read notifications text will be thinner than unread.
2. Reduced Scroll bar width across app.
3. Fixed - https://team-1624093970686.atlassian.net/browse/AR-6057

[Hotfix] - Notifications 

---

src/components/app-configure/ConfigureSidebar.vue

- Temporary hotfix: Hide global keys for testnet

[Hotfix] hide global keys on testnet (temporary)

---

src/components/AppHeader.vue
src/components/app-configure/general/AppBranding.vue
src/components/lib/VFileUpload/VFileUpload.vue
src/pages/AppDetails.vue
src/pages/AppLogin.vue

* fix brand logo upload UI.
* show only clicked menu.
Ref: https://arcana-nw.slack.com/archives/C03AXHFMNH4/p1683094123060509

[Hotfix] (#246)

---

src/stores/chainManagement.store.ts

Resolves [AR-6121](https://team-1624093970686.atlassian.net/browse/AR-6121).
Changed the code that stores fetched data.
[AR-6121]: https://team-1624093970686.atlassian.net/browse/AR-6121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] AR-6121

---

src/components/app-configure/CreateApp.vue
src/components/app-configure/chain-management/AppChainManagementForm.vue
src/components/app-configure/general/DeleteTimerPopup.vue
src/services/gateway.service.ts
src/utils/validateRPCandChainId.ts

Resolves or continues [AR-6131(https://team-1624093970686.atlassian.net/browse/AR-6131).
1. Implemented a check to see if provided RPC URL is valid and chain ID belong to RPC URL's network.
2. While creating app, implemented a check to see if the selected chain is a valid network.

[AR-6131] check for chain id with given RPC URL

---

src/services/gateway.service.ts

1. Add `id` to payload to fetch chain id of selected chain.

[Hotfix] Add id to payload

---

src/components/app-configure/chain-management/AppChainManagementForm.vue

1. Fixed Issue in the edit form for built in chains.

[Hotfix] edit chain issue.

---

src/pages/AppChainManagement.vue
src/pages/ManageApps.vue
src/services/gateway.service.ts
src/stores/chainManagement.store.ts

1. Switch URLs based on currently selected network.

add current network to api calls

---

src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/pages/AppChainManagement.vue
src/pages/AppDetails.vue
src/pages/ManageApps.vue
src/services/gateway.service.ts
src/stores/chainManagement.store.ts

1. Implemented logic to copy chain list to `mainnet` if created from `testnet` or `testnet` if created from `dev`

copy chain config

---

src/components/app-configure/auth/SocialAuth.vue
src/utils/constants.ts

1. Replace docs link for **Steam** login.
2. Add Note for **Steam** login.

[AR 6185] fixes

---

src/pages/AppDetails.vue

Resolves or continues [AR-6225](https://team-1624093970686.atlassian.net/browse/AR-6225).
Implemented code to copy chain list only when copy config is selected.
[AR-6225]: https://team-1624093970686.atlassian.net/browse/AR-6225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-6225] Fix: Chain list is copied even when new config is selected.

---

src/components/app-configure/auth/SocialAuth.vue
src/components/app-configure/chain-management/AppChainManagementForm.vue

1. Fix issue with whitespace in URLs (RPC and Explorer).
2. Replaced **Client Secret** with **Steam API Key**.

bug RPC url whitespace

---

public/auth.umd.js
src/components/app-configure/ConfigureSidebar.vue
src/stores/chainManagement.store.ts
src/utils/constants.ts

- Commented out steam login
- Updated auth SDK to resolve bugs caused by Phantom extension

Fixes for release

---

src/App.vue

Add Testnet maintenance banner.

add maintenance banner

---

src/App.vue

hotfix remove testnet down banner

---

src/components/MainnetAppCreatedPopup.vue
src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/CreateApp.vue
src/components/app-configure/auth/WebWallet.vue
src/pages/AppDetails.vue
src/services/gateway.service.ts
src/stores/apps.store.ts
src/utils/constants.ts
src/utils/createAppConfig.ts

Resolves or continues [AR-6308](https://team-1624093970686.atlassian.net/browse/AR-6308).
1. Implement code to set Wallet UI mode while creating app.
2. Show Chosen UI Mode in Wallet section.
3. Hide `keyspace` tab if Wallet UI mode is `Custom`.
[AR-6308]: https://team-1624093970686.atlassian.net/browse/AR-6308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-6308] Wallet UI mode

---

src/components/app-configure/CreateApp.vue

Resolves or continues [AR-6336](https://team-1624093970686.atlassian.net/browse/AR-6336).
1. Fix create button disable issue
[AR-6336]: https://team-1624093970686.atlassian.net/browse/AR-6336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-6336] Create app issue

---

src/components/app-configure/auth/WebWallet.vue

Resolves [AR-6355](https://team-1624093970686.atlassian.net/browse/AR-6355).
Implemented few changes to match design in Figma
design - https://www.figma.com/file/a1XBNSZs6dJ3dS1xjBQOdW/Dashboard?type=design&node-id=9599-6477&t=dYH6xPToyxf65gZd-4
[AR-6355]: https://team-1624093970686.atlassian.net/browse/AR-6355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-6355] Change UI code to match design

---

src/components/app-configure/auth/SocialAuth.vue

1. Removed condition that hides `firebase` option.

enable firebase in testnet

---

src/components/MainnetAppCreatedPopup.vue
src/components/app-configure/auth/WebWallet.vue

1. Hide Wallet-UI mode related changes for `mainnet` and `production` dashboard.

hide wallet-UI mode UI for main-net or production

---

src/components/MainnetAppCreatedPopup.vue

Remove logic that hides CTA for keyspace in Mainnet popup.

[Fix] main-net popup

---

src/components/app-configure/ConfigureSidebar.vue
src/pages/AppGasTanks.vue
src/pages/AppGasless.vue
src/router/index.ts
src/utils/constants.ts

1. Add Gas-less submenu to sidebar.

add gas-less submenu

---

src/components/app-configure/auth/SocialAuth.vue

- Enabled steam and firebase login options in mainnet

Enable steam and firebase login options

---

src/components/MainnetAppCreatedPopup.vue
src/components/app-configure/auth/WebWallet.vue

Upgrade auth sdk

---

src/use/arcanaAuth.ts

set always visible to true

---

src/components/app-configure/ConfigureSidebar.vue
src/pages/ManageApps.vue

Resolves or continues [AR-6832](https://team-1624093970686.atlassian.net/browse/AR-6832).
1. Created a utility function to apply ellipsis on app name.
2. Used the function in `src/pages/ManageApps.vue` and `src/components/app-configure/ConfigureSidebar.vue`
[AR-6832]: https://team-1624093970686.atlassian.net/browse/AR-6832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ellipsis app name

---

src/App.vue

Resolves or continues [AR-7038](https://team-1624093970686.atlassian.net/browse/AR-7038).
1. Added banner to convey backend is currently in maintenance.
[AR-7038]: https://team-1624093970686.atlassian.net/browse/AR-7038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add banner regarding maintenance

---

src/App.vue

Resolves or continues [AR-7044](https://team-1624093970686.atlassian.net/browse/AR-7044).
1. Removed banner.
[AR-7044]: https://team-1624093970686.atlassian.net/browse/AR-7044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7044] remove maintenance banner

---

package-lock.json
package.json
src/components/app-configure/CreateApp.vue
src/components/app-configure/chain-management/AppChainManagementForm.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/components/app-configure/chain-management/ChainTypeSelection.vue
src/components/lib/VDropdown/VDropdown.vue
src/pages/AppChainManagement.vue
src/pages/AppLogin.vue
src/services/gateway.service.ts
src/stores/chainManagement.store.ts
src/utils/chainTypes.ts

- Dev can choose between EVM or Solana in Chain management
- Dev cannot add a new chain in Solana
- Dev can choose which chain type he wants during app creation

Non evm solana

---

src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/components/app-configure/chain-management/ChainTypeSelection.vue
src/pages/AppChainManagement.vue
src/pages/AppDetails.vue
src/services/gateway.service.ts
src/stores/apps.store.ts
src/utils/createAppConfig.ts

Update UI according to chain selected

---

src/App.vue
src/components/app-configure/AppKeyspace.vue
src/components/app-configure/CreateApp.vue
src/components/app-configure/VerificationForm.vue
src/components/app-configure/auth/IAMProviders.vue
src/components/app-configure/auth/RedirectURI.vue
src/components/app-configure/auth/SocialAuth.vue
src/components/app-configure/auth/SocialAuthProvider.vue
src/components/app-configure/auth/WebWallet.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/components/app-configure/gasless/AppGasTankDeposit.vue
src/components/app-configure/gasless/AppGaslessSmartContractForm.vue
src/components/app-configure/general/AppDelete.vue
src/components/app-configure/general/AppName.vue
src/components/app-configure/general/WalletTheme.vue
src/components/app-configure/store/UserLimits.vue
src/pages/AppChainManagement.vue
src/pages/AppDashboard.vue
src/pages/AppDetails.vue
src/pages/AppGasTanks.vue
src/pages/AppInvoices.vue
src/pages/AppLogin.vue
src/pages/AppProfile.vue
src/utils/content.ts
tsconfig.app.json

Developer Dashboard- Single File for Error 
Added Error Logs over a Local File to Ease Logging the Error and Preview Content for interactions.
[AR-7245]: https://team-1624093970686.atlassian.net/browse/AR-7245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Single File for Error Messages Dashboard

---

src/components/app-configure/chain-management/AppChainManagementForm.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/stores/chainManagement.store.ts

Resolves or continues [AR-7508](...).
[AR-7508]: https://team-1624093970686.atlassian.net/browse/AR-7508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chain Exists Error Log on adding an existing chain.

---

src/components/app-configure/chain-management/AppChainManagementList.vue
src/stores/chainManagement.store.ts

Resolves or continues [AR-7560](...).
This adds a button-triggered functionality allowing users to reorder their selected chains in the Developer Dashboard.
https://github.com/arcana-network/developer-dashboard/assets/77049812/cec61ae0-614e-409f-8b81-7a4f14fd5295
[AR-7560]: https://team-1624093970686.atlassian.net/browse/AR-7560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Customisable Chain Ordering on Dashboard Implemented.

---

src/components/app-configure/chain-management/AppChainManagementForm.vue

Resolves or continues [AR-7508](...).
Disabled the Add Chain Button if a user tries to add a Chain Already present.
[AR-7508]: https://team-1624093970686.atlassian.net/browse/AR-7508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Same-Chain-Error-QA-Review

---

src/utils/content.ts

Resolves or continues [AR-7245](...).
[AR-7245]: https://team-1624093970686.atlassian.net/browse/AR-7245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Error Logs - Framing and Typos Corrected

---

src/components/app-configure/VerificationForm.vue

- Show toast error messages instead of returning errors to void for verification form

Show toast errors for verification form

---

src/components/app-configure/gasless/AppGasTankForm.vue

Resolves or continues [AR-7900](https://team-1624093970686.atlassian.net/browse/AR-7900).
1. Inform user to install metamask if its not installed.
[AR-7900]: https://team-1624093970686.atlassian.net/browse/AR-7900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7900] Implement UI to inform user to install metamask

---

src/components/AppFooter.vue
src/components/LoginFooter.vue
src/components/lib/VButtonSecondary/VButtonSecondary.vue
src/components/lib/VTextFieldSecondary/VTextFieldSecondary.vue
src/pages/AppLogin.vue

Resolves or continues [AR-7798](...).
Re-Did the components used throughout the dashboard.
[AR-7798]: https://team-1624093970686.atlassian.net/browse/AR-7798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Login Component Fixes

---

src/components/app-configure/auth/AuthSettings.vue

[Hotfix] hide custom verifier UI

---

src/components/app-configure/auth/CustomVerifier.vue

Resolves or continues [AR-7928](https://team-1624093970686.atlassian.net/browse/AR-7928).
1. Made validation field options
2. Other functionality fixes
[AR-7928]: https://team-1624093970686.atlassian.net/browse/AR-7928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-7928] make validation fields optional

---

src/components/app-configure/auth/CustomVerifier.vue

1. Change structure of Id params

change structure of params

---

src/components/app-configure/auth/CustomVerifier.vue

1. Change from Array to Object in params prop.

change to object from array

---

src/components/app-configure/auth/CustomVerifier.vue

1. Implement fix issue regarding validation field.

fix validation field issues

---

src/components/app-configure/auth/AuthSettings.vue

enable custom verifier

---

src/components/app-configure/auth/AuthSettings.vue

1. Import custom verifier component

[BugFix] import custom verifier component

---

src/components/app-configure/auth/AuthSettings.vue

Show Custom verifier UI only for Testnet apps

show only for testnet apps

---

.vscode/settings.json
package-lock.json
package.json
src/assets/close.svg
src/components/AppOverlay.vue
src/components/OTPInput.vue
src/components/app-configure/VerificationForm.vue
src/components/app-configure/auth/WebWallet.vue
src/components/app-configure/chain-management/AppChainManagementForm.vue
src/pages/AppLogin.vue
src/use/arcanaAuth.ts
src/utils/validation.ts
tailwind.config.js

Resolves or continues [AR-7719](...).
Added OTP Login Flow on Dev Dashboard.
[AR-7719]: https://team-1624093970686.atlassian.net/browse/AR-7719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTP Flow Added

---

src/components/app-configure/chain-management/AppChainManagementList.vue
src/services/gateway.service.ts
src/stores/chainManagement.store.ts
src/utils/chainTypes.ts

add near support

---

src/App.vue
src/components/LandingDescriptor.vue
src/components/OTPInput.vue
src/pages/AppLogin.vue
tailwind.config.js

- Used tailwind classes instead of inline styles
- Fix login with top issue
- Avoid using generative tailwind classes, instead moved them to tailwind config
- Fixed responsiveness

Fix login page issues

---

src/App.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/pages/AppDetails.vue
src/services/gateway.service.ts

- Remove unused imports
- Fix component naming
- Avoid multiroot page components, so transition gets only 1 root to play with
- fix `get-mau`

Fix vue routing issue

---

src/components/AppHeader.vue
src/components/AppNotifications.vue
src/components/app-configure/auth/AuthSettings.vue
src/components/icons/NotificationIcon.vue
src/pages/AppLogin.vue

Deploy Prod Bug Fixes for [AR-8126, 8127 & 8130]

Fix: Deploy Prod Bug Fixes for [AR-8126, 8127 & 8130]

---

src/components/app-configure/chain-management/AppChainManagementList.vue
src/components/lib/styles.css
src/pages/AppChainManagement.vue

> Chainlist Options Updated
> Scrollbar Design Updated
> ChainType Text Added
> ChainManagement List Width Issue Fixed

Dashboard Fixes: Chain List Options Update, Scrollbar Design Updated, ChainType Text Added

---

src/services/gateway.service.ts
src/stores/chainManagement.store.ts
src/utils/chainTypes.ts

[Feature-Testnet] Near Support

---

src/components/app-configure/AppKeyspace.vue
src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/CreateApp.vue
src/components/app-configure/auth/CustomVerifier.vue
src/components/app-configure/auth/RedirectURI.vue
src/components/app-configure/gasless/AppGaslessTankList.vue
src/components/icons/CloseIcon.vue
src/components/lib/VDropdown/VDropdown.vue
src/components/lib/VDropdownSecondary/VDropdownSecondary.vue
src/components/lib/VFileUpload/VFileUpload.vue
src/components/lib/VTextFieldSecondary/VTextFieldSecondary.vue
src/pages/ManageApps.vue
tailwind.config.js

- Redirect URI Spacing Updated
- Custom Verifier UI (Text and Icons Fixed)
- Gasless Page Width Tweaked
- Secondary Text Field Padding Fixed
- Dropdown Arrow Animations Updated
- Arrange Chains by Alphabetical Order over Create App Form.
- App Card Updated (Hover Effect Added)
- Sidebar Icon Alignment
- Upload Input Updated as per Design Theme
- Card Component Disabled State Styling
[AR-8190]: https://team-1624093970686.atlassian.net/browse/AR-8190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prod Bug Fixes

---

src/assets/iconography/session.svg
src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/SettingCard.vue
src/components/lib/VTextField/VTextField.vue
src/components/lib/VTextFieldSecondary/VTextFieldSecondary.vue
src/pages/AppDownNotification.vue
src/pages/AppSessionManagement.vue
src/router/index.ts
src/services/gateway.service.ts
src/stores/apps.store.ts
src/utils/content.ts
src/utils/createAppConfig.ts

- Session Management Page Added.
- Minor Bug Fixes ( Suggested Web Input Bg Fixed, Maintenance Page UI Fixed)
[AR-8050]: https://team-1624093970686.atlassian.net/browse/AR-8050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: Session Management Implemented

---

src/pages/AppSessionManagement.vue

Chore: Sessions Management Page Content Fixes

---

src/components/app-configure/ConfigureSidebar.vue

Hotfix: Reinstated Session Changes on Dashboard

Hotfix: Reinstated Session Changes on Dashboard

---

src/pages/AppProfile.vue

Resolves [AR-8078](https://team-1624093970686.atlassian.net/browse/AR-8078).
1. Commented out Billing address details card
[AR-8078]: https://team-1624093970686.atlassian.net/browse/AR-8078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-8078] hide billing address details card

---

src/components/app-configure/AppKeyspace.vue

Resolves or continues [AR-8207](https://team-1624093970686.atlassian.net/browse/AR-8207).
1. Remove verification step to switch to Global keyspace.
[AR-8207]: https://team-1624093970686.atlassian.net/browse/AR-8207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-8207] impl logic to switch to global without verification

---

src/components/app-configure/auth/CustomVerifier.vue

1. Don't fetch custom providers if the app key-space is global

[hotfix] don't fetch if its global

---

src/components/app-configure/CreateApp.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/services/gateway.service.ts
src/stores/chainManagement.store.ts
src/utils/constants.ts

Resolves or continues [AR-8226](...).
[AR-8226]: https://team-1624093970686.atlassian.net/browse/AR-8226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: Added Shards Value for MVX Apps

---

src/components/app-configure/chain-management/AppChainManagementList.vue

Resolves or continues [AR-8226](...).
- Hotfix: Shard Value when Global Keyspace
[AR-8226]: https://team-1624093970686.atlassian.net/browse/AR-8226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hotfix: Shard Value when Global Keyspace

---

src/components/app-configure/AppKeyspace.vue
src/components/app-configure/ConfigureSidebar.vue
src/components/app-configure/CreateApp.vue
src/components/app-configure/auth/CustomVerifier.vue
src/components/app-configure/chain-management/AppChainManagementList.vue
src/pages/AppProfile.vue
src/pages/AppSessionManagement.vue
src/services/gateway.service.ts
src/stores/chainManagement.store.ts
src/utils/constants.ts

Resolves or continues [AR-8226](...).
[AR-8226]: https://team-1624093970686.atlassian.net/browse/AR-8226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: Specify Shard Value for MVX Apps

---

src/components/app-configure/auth/RedirectURI.vue

separator issue fix

---

src/components/app-configure/auth/RedirectURI.vue

separator issue fix (#437)

---

src/components/app-configure/auth/WebWallet.vue

Resolves or continues [AR-8506](...).
Added Notes to Web Wallet Domain
[AR-8506]: https://team-1624093970686.atlassian.net/browse/AR-8506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore:Added Changes Note to Web Wallet Domain + Removed Inline Stylings

---

src/components/app-configure/auth/AuthProviderInput.vue

Resolves or continues [AR-XXX](...).
- [AR-YYY](...)
- [AR-ZZZ](...)
Please include a summary of the changes and any relavant context not convered in the issue ticket. You can assume that reviewers will begin by reading the description of the linked issue.
When making primarily visual changes, it's helpful to include before and after screenshots.

Fix: Layout and Prod Issues on Apple Login

---

src/components/app-configure/auth/AuthProviderInput.vue

Resolves or continues [AR-XXX](...).
- [AR-YYY](...)
- [AR-ZZZ](...)
Please include a summary of the changes and any relavant context not convered in the issue ticket. You can assume that reviewers will begin by reading the description of the linked issue.
When making primarily visual changes, it's helpful to include before and after screenshots.

Fix: Layout and Prod Issues on Apple Login (#442)

---

package-lock.json
src/components/app-configure/chain-management/AppChainManagementList.vue

Resolves or continues [AR-8111](...).
Fix dashboard chain management width and added only one class for this. This is only style change.
[AR-8111]: https://team-1624093970686.atlassian.net/browse/AR-8111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Dashboard Chain Management Width

---

src/components/app-configure/ConfigureActionButtons.vue

Resolves or continues [AR-8607](...).
Placement of Cancel Button in Social Auth Tab.
[AR-8607]: https://team-1624093970686.atlassian.net/browse/AR-8607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Placement of Cancel Button in Social Auth Tab

---

src/components/app-configure/auth/PasskeysProviders.vue
src/utils/constants.ts

Resolves or continues [AR-8618](...).
Change Fn Name, Link and Text Updated in Passkey Provider.
[AR-8618]: https://team-1624093970686.atlassian.net/browse/AR-8618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Change Fn Name, Link and Text Updated
