vite.config.js
**Changes**
Sets `build.sourcemap` field to true in vite's config. Note that we need to keep `sourceMappingURL` for Sentry.
Resolves AR-766.
=> Generate source maps on build

src/pages/AppProfile.vue, src/pages/AppUsers.vue
Renamed 'Email' to 'Public Identifier' in profile page and user details popup. There are cases in Github SSO and Discord SSO where sometimes we don't get user's email as identifier, instead we get a unique numeric id and we use that for fetching/ generating keys.
ref: https://team-1624093970686.atlassian.net/browse/AR-856?atlOrigin=eyJpIjoiNjRmNWQ5MTVmYjhhNDI3NWFjOWY1NDA0OTc0NmQ3MWQiLCJwIjoiaiJ9
=> Renamed Email to Public Identifier in profile page and user details

src/pages/AppConfigure.vue, src/pages/AppLoginV2.vue, src/pages/AppNewPassword.vue
1. Replaced heading content and removed subheading
2. Added a link to why create password and on click of that link opens a popup describing the reason
3. Added a password description popup
4. Added a link to skip the password creation and on skip click, it stores the user preference in session storage (TBD if we need it in session storage or local storage) and redirects user to dashboard
5. In App login, if user preference is stored in session storage, he won't be provided with password creation screen
6. Replaced relative imports with root relative imports
=> Ar 1119 update password screen content

src/pages/AppConfigure.vue
Resolves [AR-1019](https://team-1624093970686.atlassian.net/browse/AR-1019).
1. Added a function that resets the changes that aren't saved
2. Added the reset function call in backToDashboard handler
3. Refactored onFooterCancel handler
=> Fixed config changes on back click

src/components/app-configure/AppChain.vue
Resolves [AR-859](https://team-1624093970686.atlassian.net/browse/AR-859).
1. Removed "if" block.
2. Used the value from **check** event to set name of the chain type.
=> [Fix] - AR-859 - Save Button Does Not Appear On Reconfiguration of Chains

src/services/app-config.service.js, src/services/auth.service.js
Resolves or continues [AR-1425](https://team-1624093970686.atlassian.net/browse/AR-1425).
Replaced `getEnvApi(false)` to `getEnvApi`
`getEnvApi(false)` returns unversioned apis
`getEnvApi()` returns current version api as specified in `.env` eg: `v1`
`getEnvApi(version)` returns api of specified version. eg: `getEnvApi('v2')` returns apis with version `v2`
=> Replaced pending unversioned apis with versioned apis

public/tx-sign.js, src/components/app-configure/auth/SocialAuth.vue, src/components/app-configure/auth/WebWallet.vue, src/components/app-configure/store/UserLimits.vue, src/pages/AppConfigure.vue, src/services/smart-contract.service.ts, src/store/app.store.ts, src/utils/constants.ts, src/utils/signerMakeTx.ts
Resolves [AR-2551](https://team-1624093970686.atlassian.net/browse/AR-2551).
- Add updated DashboardSigner
- Add disable condition on switch after UI mode is enabled
- Hide theme selection and preview images if UI mode is disabled
- Add WalletModeMapping enum
- Make `value` optional in signerMakeTx
- Add `enableUIMode` smart contract call
- Make smart contract calls only if changes are detected for single values
=> Add UI-NoUI implementation

src/components/app-configure/access/ChainType.vue, src/store/app.store.ts, src/utils/constants.ts
Resolves [AR-2783](https://team-1624093970686.atlassian.net/browse/AR-2783).
- Add 'none' option in ChainOptions
- Map 'none' option to value 3
- Replace radiobutton with dropdown for chain selection
- Set default chain type as 'none' while creating app
- Update the logic to make it work for the dropdown
**Before**
**After**
=> Change Chain Type UI from Radio Buttons to Dropdown

src/components/app-configure/auth/WebWallet.vue, src/pages/AppConfigure.vue, src/pages/AppDashboard.vue, src/store/app.store.ts
Resolves [AR-2785](https://team-1624093970686.atlassian.net/browse/AR-2785).
- Add `hasWalletUIModeInGateway` state variable to store the value of `wallet_type` present in server
- Add mutation and getter to that variable
- Disable switch if that state variable is true
- [refactor] Change route to users in Dashboard to named route
=> Allow UI Mode toggle if not saved on server

src/store/app.store.ts
Resolves [AR-2949](https://team-1624093970686.atlassian.net/browse/AR-2949).
- Add trailing slash to redirect uri
=> Add trailing slash to redirect uri

src/pages/AppDashboard.vue
Resolves [AR-2954](https://team-1624093970686.atlassian.net/browse/AR-2954).
- Add storage and bandwidth usage, remaining and percentage values
- Update `transfers` to `ownership_change`
Before Changes
After changes
=> Add storage and bandwidth usage, remaining and percentage values

src/components/app-configure/CreateApp.vue, src/components/app-configure/store/StorageRegion.vue, src/components/lib/VTooltip/VTooltip.vue
Resolves [AR-3179](https://team-1624093970686.atlassian.net/browse/AR-3179).
- Make certain text related to storage region selection bold
=> Make certain text related to storage region selection bold

src/components/app-configure/CreateApp.vue, src/pages/AppConfigure.vue
- Signer was not getting updated after creating new app. So added `createTransactionSigner`, everytime we do fetch app details
=> Create signer everytime after fetching app config

package-lock.json, package.json, src/components/app-configure/CreateApp.vue, src/pages/ManageApps.vue, src/stores/apps.store.ts, src/use/arcanaAuth.ts
Resolves [AR-4227](https://team-1624093970686.atlassian.net/browse/AR-4227).
- Update auth sdk to 0.1.2-beta.8
- Fixed default selected theme to dark mode
- Fixed redirectURL to redirectUrl
=> Update auth sdk to 0.1.2-beta.8

src/components/AppHeader.vue, src/components/lib/VHeader/VHeader.vue
Resolves [AR-4324](https://team-1624093970686.atlassian.net/browse/AR-4324).
- Add link to go back to manage apps screen.
- Disable dashboard and users pages when on manage apps or profile screens.
https://user-images.githubusercontent.com/11095038/190320554-9b849f27-c320-4d1a-9ec7-0238cd5d8adb.mov
=> Add temporary navigation fixes on dev dashboard

package-lock.json, package.json, src/pages/AppLogin.vue
Resolves [AR-4335](https://team-1624093970686.atlassian.net/browse/AR-4335).
- Update auth sdk to `0.1.2-beta.10` to support passwordless login in NoUI mode
- Wrap login flow in try catch block and hide loader if user closes the popup
=> AR-4335 Update auth sdk beta.10

src/components/app-configure/auth/SocialAuth.vue, src/stores/apps.store.ts, src/utils/constants.ts
Resolves [AR-4516](https://team-1624093970686.atlassian.net/browse/AR-4516).
- Removed redirectUri from social auth as it is not required anymore. Previously it was required for twitter login
Before
After
=> Remove redirect uri from social auth

src/pages/AppDashboard.vue
Hotfix for [AR-4808](https://team-1624093970686.atlassian.net/browse/AR-4808)
Copy app address instead of app id
=> Hotfix for AR-4808 - Copy app address instead of app id

src/components/app-configure/access/DidDelegate.vue
- Hide titles/name in large screens
**Before**
**After**
=> Hotfix: Hide titles in large screens

src/components/app-configure/access/CreateOrEditDelegate.vue
Resolves [AR-5108](https://team-1624093970686.atlassian.net/browse/AR-5108).
- Show key name instead of address on select key dropdown
- Add whitespace nowrap to dropdown input so it doesn't wrap to next line on overflow
=> AR-5108 Show key name instead of address on key dropdown

src/pages/AppLogin.vue, src/use/arcanaAuth.ts
- Use "connect" event to wait until wallet provider is connected, else fetching user details from wallet fails as wallet is not connected
=> [HOTFIX] - Use "connect" event to wait until wallet provider is connected

src/components/MainnetAppCreatedPopup.vue, src/components/SwitchToMainnetConfirmation.vue, src/components/app-configure/ConfigureSidebar.vue, src/components/app-configure/VerificationForm.vue, src/pages/AppDashboard.vue, src/pages/AppDetails.vue, src/pages/ManageApps.vue, src/services/gateway.service.ts, src/utils/constants.ts
Resolves [AR-5832](https://team-1624093970686.atlassian.net/browse/AR-5832).
- Separate out dev, testnet, and mainnet in the dashboard where 
- Dev environment will have `dev` and `testnet`
- Prod environment will have `testnet` and `mainnet`
- Switching the keyspace will also be available in `dev` and `testnet`. Previously it was only available in `mainnet`
[AR-5832]: https://team-1624093970686.atlassian.net/browse/AR-5832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [AR-5832] Separate out dev testnet mainnet

src/components/AppNotifications.vue
Resolves or continues [AR-5945](https://team-1624093970686.atlassian.net/browse/AR-5945).
1. Show timestamp of notifications in relative time (Eg: 4 days ago, 1 second ago).
[AR-5945]: https://team-1624093970686.atlassian.net/browse/AR-5945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [AR-5945] show notification time as relative time

src/components/app-configure/auth/SocialAuth.vue
Bug: **Steam** client Id is uploaded even without selecting its tab.
Fix: Check if **Steam** tab is selected before adding app address.
=> [Bug] add client Id only for Steam is selected
